const baseUrl = '/languages/';
export const languages = [
    { value: '-- Select --', label: '-- Select --'},
    { value: 'Automatic detection', label: 'Automatic detection' },
    { value: 'Pascal', label: 'Pascal' },
    { value: 'JavaScript', label: 'JavaScript', src: baseUrl +  'javascript.png', alt: 'JavaScript Code Converter' },
    { value: 'TypeScript', label: 'TypeScript', src: baseUrl +  'typescript.png', alt: 'TypeScript Code Converter' },
    { value: 'Python', label: 'Python', src: baseUrl +  'python.png', alt: 'Python Code Converter' },
    { value: 'TSX', label: 'TSX' },
    { value: 'JSX', label: 'JSX' },
    { value: 'Vue', label: 'Vue', src: baseUrl +  'vue.png', alt: 'Vue Code Converter' },
    { value: 'Go', label: 'Go', src: baseUrl +  'go.png', alt: 'Go Code Converter' },
    { value: 'C', label: 'C', src: baseUrl +  'c.png', alt: 'C Code Converter' },
    { value: 'C++', label: 'C++', src: baseUrl +  'cpp.png', alt: 'C++ Code Converter' },
    { value: 'Java', label: 'Java', src: baseUrl +  'java.png', alt: 'Java Code Converter' },
    { value: 'C#', label: 'C#', src: baseUrl +  'csharp.png', alt: 'C# Code Converter' },
    { value: 'Visual Basic .NET', label: 'Visual Basic .NET', src: baseUrl +  'vbnet.png', alt: 'Visual Basic .NET Code Converter' },
    { value: 'SQL', label: 'SQL', src: baseUrl +  'sql.png', alt: 'SQL Code Converter' },
    { value: 'Assembly Language', label: 'Assembly Language' },
    { value: 'PHP', label: 'PHP', src: baseUrl +  'php.png', alt: 'PHP Code Converter' },
    { value: 'Ruby', label: 'Ruby', src: baseUrl +  'ruby.png', alt: 'Ruby Code Converter' },
    { value: 'Swift', label: 'Swift', src: baseUrl +  'swift.png', alt: 'Swift Code Converter' },
    { value: 'SwiftUI', label: 'SwiftUI' },
    { value: 'Kotlin', label: 'Kotlin', src: baseUrl +  'kotlin.png', alt: 'Kotlin Code Converter' },
    { value: 'R', label: 'R', src: baseUrl +  'r.png', alt: 'R Code Converter' },
    { value: 'Objective-C', label: 'Objective-C', src: baseUrl +  'objc.png', alt: 'Objective-C Code Converter' },
    { value: 'Perl', label: 'Perl', src: baseUrl +  'perl.png', alt: 'Perl Code Converter' },
    { value: 'SAS', label: 'SAS' },
    { value: 'Scala', label: 'Scala', src: baseUrl +  'scala.png', alt: 'Scala Code Converter' },
    { value: 'Dart', label: 'Dart' },
    { value: 'Rust', label: 'Rust', src: baseUrl +  'rust.png', alt: 'Rust Code Converter' },
    { value: 'Haskell', label: 'Haskell', src: baseUrl +  'haskell.png', alt: 'Haskell Code Converter' },
    { value: 'Lua', label: 'Lua', src: baseUrl +  'lua.png', alt: 'Lua Code Converter' },
    { value: 'Groovy', label: 'Groovy', src: baseUrl +  'groovy.png', alt: 'Groovy Code Converter' },
    { value: 'Elixir', label: 'Elixir' },
    { value: 'Clojure', label: 'Clojure' },
    { value: 'Lisp', label: 'Lisp' },
    { value: 'Julia', label: 'Julia' },
    { value: 'Matlab', label: 'Matlab', src: baseUrl +  'matlab.png', alt: 'Matlab Code Converter' },
    { value: 'Fortran', label: 'Fortran' },
    { value: 'COBOL', label: 'COBOL' },
    { value: 'Bash', label: 'Bash', src: baseUrl +  'bash.png', alt: 'Bash Code Converter' },
    { value: 'Shell', label: 'Shell', src: baseUrl +  'shell.png', alt: 'Shell Code Converter' },
    { value: 'Powershell', label: 'Powershell', src: baseUrl +  'powershell.png', alt: 'Powershell Code Converter' },
    { value: 'PL/SQL', label: 'PL/SQL', src: baseUrl +  'plsql.png', alt: 'PL/SQL Code Converter' },
    { value: 'CSS', label: 'CSS', src: baseUrl +  'css.png', alt: 'CSS Code Converter' },
    { value: 'Racket', label: 'Racket' },
    { value: 'HTML', label: 'HTML', src: baseUrl +  'html.png', alt: 'HTML Code Converter' },
    { value: 'NoSQL', label: 'NoSQL' },
    { value: 'Natural Language', label: 'Natural Language' },
    { value: 'CoffeeScript', label: 'CoffeeScript' },
    { value: 'Morse Code', label: 'Morse Code', src: baseUrl +  'morsecode.png', alt: 'Morse Code Code Converter' },
    { value: 'Hex Code', label: 'Hex Code', src: baseUrl +  'hexcode.png', alt: 'Hex Code Code Converter' },
    { value: 'Binary Code', label: 'Binary Code', src: baseUrl +  'binarycode.png', alt: 'Binary Code Code Converter' },
    { value: 'Decimal Code', label: 'Decimal Code' },
    { value: 'Pseudo Code', label: 'Pseudo Code' },
    { value: 'Android', label: 'Android Code', src: baseUrl +  'android.png', alt: 'Android Code Converter' },
    { value: 'MySQL', label: 'MySQL', src: baseUrl +  'mysql.png', alt: 'MySQL Code Converter' },
    { value: 'FlinkSql', label: 'FlinkSql' },
    { value: 'Regular', label: 'Regular expression' },
    { value: 'Arduino', label: 'Arduino', src: baseUrl +  'arduino.png', alt: 'Arduino Code Converter' },
    { value: 'Esp 8266', label: 'Esp 8266', src: baseUrl +  'esp8266.png', alt: 'Esp 8266 Code Converter' },
    { value: 'Esp 32', label: 'Esp 32', src: baseUrl +  'esp32.png', alt: 'Esp 32 Code Converter' },
    { value: 'React', label: 'React', src: baseUrl +  'react.png', alt: 'React Code Converter' },
    { value: 'HTML JS CSS', label: 'HTML JS CSS', src: baseUrl +  'htmljscss.png', alt: 'HTML JS CSS Code Converter' },
    { value: 'Tailwind', label: 'Tailwind', src: baseUrl +  'tailwind.png', alt: 'Tailwind Code Converter' },
    { value: 'Git', label: 'Git' },
    { value: 'SVN', label: 'SVN' },
    { value: 'Linux', label: 'Linux' },
    { value: 'Spring', label: 'Spring' },
    { value: 'Redis', label: 'Redis' },
    { value: 'SpringBoot', label: 'SpringBoot' },
    { value: 'Next.js', label: 'Next.js', src: baseUrl +  'nextjs.png', alt: 'Next.js Code Converter' },
    { value: 'MongoDB', label: 'MongoDB', src: baseUrl +  'mongodb.png', alt: 'MongoDB Code Converter' },
    { value: 'PostgreSQL', label: 'PostgreSQL', src: baseUrl +  'postgresql.png', alt: 'PostgreSQL Code Converter' },
    { value: 'Angular', label: 'Angular', src: baseUrl +  'angular.png', alt: 'Angular Code Converter' },
    { value: 'Node.js', label: 'Node.js', src: baseUrl +  'nodejs.png', alt: 'Node.js Code Converter' },
    { value: 'Django', label: 'Django', src: baseUrl +  'django.png', alt: 'Django Code Converter' },
    { value: 'Ruby on Rails', label: 'Ruby on Rails' },
    { value: 'Memcached', label: 'Memcached' },
    { value: 'Ehcache', label: 'Ehcache' },
    { value: 'Kafka', label: 'Kafka' },
    { value: 'RabbitMQ', label: 'RabbitMQ' },
    { value: 'ActiveMQ', label: 'ActiveMQ' },
    { value: 'RocketMQ', label: 'RocketMQ' },
    { value: 'Spring Cloud', label: 'Spring Cloud' },
    { value: 'Google Cloud', label: 'Google Cloud' },
    { value: 'Chrome Extension', label: 'Chrome Extension' },
    { value: 'Docker', label: 'Docker', src: baseUrl +  'docker.png', alt: 'Docker Code Converter' },
    { value: 'Kubernetes', label: 'Kubernetes', src: baseUrl +  'kubernetes.png', alt: 'Kubernetes Code Converter' },
    { value: 'Jenkins', label: 'Jenkins' },
    { value: 'Travis CI', label: 'Travis CI' },
    { value: 'GitLab CI', label: 'GitLab CI' },
    { value: 'ELK Stack', label: 'ELK Stack' },
    { value: 'Splunk', label: 'Splunk' },
    { value: 'Spring Security', label: 'Spring Security' },
    { value: 'Shiro', label: 'Shiro' },
    { value: 'Selenium', label: 'Selenium' },
    { value: 'JWT', label: 'JWT' },
    { value: 'Three.js', label: 'Three.js' },
    { value: 'ALL Program', label: 'ALL Program' },
];